name: regenerate

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: make deps
      - run: make build
        env:
          GHD_GH_USERNAME: ${{ github.repository_owner }}
          GHD_GH_PASSWORD: ${{ secrets.GHD_GH_PASSWORD }}
          GHD_GH_TOTP_SECRET: ${{ secrets.GHD_GH_TOTP_SECRET }}
